2023-04-12 15:18:55,875 - INFO -   File "C:\Users\Kry\anaconda3\envs\cuda\lib\site-packages\trixi\experiment\experiment.py", line 90, in run
    self.validate(epoch=self._epoch_idx)

  File "D:\Projects\CS598\DLH\DLH-Term-Project\models\experiment_template.py", line 223, in validate
    self.test()

  File "D:\Projects\CS598\DLH\DLH-Term-Project\models\experiment_template.py", line 256, in test
    y_hat_los, y_hat_mort = self.model(padded, diagnoses, flat)

  File "C:\Users\Kry\anaconda3\envs\cuda\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\Projects\CS598\DLH\DLH-Term-Project\models\tpc_model.py", line 619, in forward
    combined_features = cat((flat.repeat_interleave(T - time_before_pred, dim=0),  # (B * (T - time_before_pred)) * no_flat_features

2023-04-12 15:18:55,875 - INFO - OutOfMemoryError('CUDA out of memory. Tried to allocate 142.00 MiB (GPU 0; 10.00 GiB total capacity; 6.97 GiB already allocated; 0 bytes free; 9.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')
